AY2223S1-CS2103T-T12-4/tp

docs/DeveloperGuide.md
Update use cases for the list task and view task features
=> Update use cases in the Developer Guide for v1.2

docs/UserGuide.md
=> Remove existing content from Quick Start in User Guide

README.md
=> Update description to match project direction and build status badge in README for v1.2

docs/_config.yml, docs/_sass/minima/_base.scss, docs/index.md
=> Change project site header from AB-3 to UniNurse

docs/DeveloperGuide.md
=> Remove ZWSP characters from Developer Guide

docs/DeveloperGuide.md
=> Add non-functional requirements to Developer Guide

docs/DeveloperGuide.md
=> Update DG with delete task and list patients use cases

docs/UserGuide.md
=> Replace edit with editPatient in UserGuide

docs/DeveloperGuide.md
=> Add full stops to use cases in developer guide

src/main/java/seedu/address/commons/util/StringUtil.java, src/test/java/seedu/address/commons/util/StringUtilTest.java
Implemented partial word match for find feature. Adapted test case as well since it was made for full word matching.
=> Feature find (partial word match)

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/AddTaskCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java, src/main/java/seedu/address/logic/commands/EditPatientCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/task/Task.java, src/main/java/seedu/address/model/task/TaskList.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/storage/JsonAdaptedTask.java, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java
Closes #25.
This PR adds the `deleteTask` command to UniNurse. This feature deletes a task from a specified `Person` since the `Patient` class has yet to be implemented. Note that tests for `deleteTask` and its related `Command` and `Parser` classes have not been written. GUI does not support tasks yet, so tasks do not show up on the GUI. This feature was implemented as a branch created off PR #122, so there are duplicated files.
=> Feature delete task

src/main/java/seedu/address/logic/commands/AddTaskCommand.java, src/main/java/seedu/address/logic/commands/EditPatientCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/task/Task.java, src/main/java/seedu/address/model/task/TaskList.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/storage/JsonAdaptedTask.java, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java
Closes #119, closes #41.
This PR adds the `addTask` command to UniNurse. This feature adds a task to a specified `Person` since the `Patient` class has yet to be implemented. Note that tests for `addTask` and other related classes such as `Task` and `TaskList` have not been written. GUI is also not updated here, so while tasks can be added, they will not show up on the GUI.
=> Feature add task

docs/UserGuide.md
Changed find feature description from full word match to partial word match
=> Fix find description in UG

docs/DeveloperGuide.md
Closes #93. Also resolves #125
=> Add numbering to use cases in developer guide

build.gradle
=> Update addressbook.jar to uninurse.jar in build.gradle file

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/ListTaskCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/main/java/seedu/address/ui/TaskListCard.java, src/main/resources/view/TaskListCard.fxml, src/test/java/seedu/address/logic/commands/AddCommandTest.java
Add ListTask feature with GUI updates
=> Add ListTask feature

src/main/java/seedu/address/logic/commands/AddPatientCommand.java, src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/TaskDescription.java
This PR adds the addPatient command to UniNurse, you can test the command by following the User guide for addPatient. Note that patient model has not been fleshed out yet so for now this simply adds a person with the given details to address book.
=> Feature add patient

src/main/java/seedu/address/logic/commands/AddPatientCommand.java, src/main/java/seedu/address/logic/commands/DeletePatientCommand.java, src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/DeletePatientCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/TaskDescription.java
This PR adds the deletePatient command to UniNurse, you can test the command by following the User guide for deletePatient. Note that patient model has not been fleshed out yet so for now this simplydelete a person with the given index from the address book.
=> Feature delete patient

src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java, src/main/java/seedu/address/logic/commands/EditTaskCommand.java, src/main/java/seedu/address/model/task/TaskList.java
This change makes the `TaskList` immutable. The corresponding `DeleteTaskCommand` class is also updated.
=> Update `TaskList#delete` to return a `TaskList`

src/main/java/seedu/address/logic/commands/EditTaskCommand.java, src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java, src/test/java/seedu/address/logic/parser/EditTaskCommandParserTest.java
I made a mistake and resolved the test conflicts in this branch instead of tests-editTask_tests. This should be up to date with all the changes made to master so please ignore the previous PR for tests-editTask_tests and review this one
=> Resolve test failures

src/main/java/seedu/address/model/GenericList.java, src/main/java/seedu/address/model/task/TaskList.java
Closes #165 
This PR adds a `GenericList<T>` interface to encapsulate multi-valued attributes of the `Person` class.
=> Feature add generic list

src/test/java/seedu/address/model/tag/TagTest.java, src/test/java/seedu/address/model/task/TaskTest.java
This PR adds unit tests in the `TaskTest` class and updates the unit tests `TagTest` to cover more types of valid and invalid inputs.
=> Feature add `TaskTest` and update `TagTest`

src/main/java/seedu/uninurse/logic/commands/PatientsTodayCommand.java, src/main/java/seedu/uninurse/logic/parser/AddTaskCommandParser.java
Fixed the bug where date time is not created for added tasks and also a minor bug where patientsToday command does not show the tasks (it only showed the patients with tasks today)
=> Bugfix for add tasks

src/main/java/seedu/uninurse/model/condition/ConditionList.java, src/main/java/seedu/uninurse/model/task/TaskList.java
Closes #187 
The following methods are added as they will be used in the `Patient` class:
- Added `ConditionList#equals()`
- Added `ConditionList#toString()`
- Added `ConditionList#hashCode()`
Unrelated fixes since they are quite minor and do not warrant a new PR:
- Capitalisation in JavaDoc comment of `TaskList#getAllTasksToday()`
- Modified JavaDoc comment of `TaskList#containsTaskToday()`
=> Fix: Change `ArrayList<Condition>` to `List<Condition>` in `ConditionList`

src/main/java/seedu/uninurse/commons/core/Config.java, src/main/java/seedu/uninurse/logic/LogicManager.java, src/main/java/seedu/uninurse/logic/commands/AddGenericCommand.java, src/main/java/seedu/uninurse/logic/commands/ClearCommand.java, src/main/java/seedu/uninurse/logic/commands/Command.java, src/main/java/seedu/uninurse/logic/commands/DeleteGenericCommand.java, src/main/java/seedu/uninurse/logic/commands/EditGenericCommand.java, src/main/java/seedu/uninurse/logic/commands/RedoCommand.java, src/main/java/seedu/uninurse/logic/commands/UndoCommand.java, src/main/java/seedu/uninurse/logic/commands/UndoableCommand.java, src/main/java/seedu/uninurse/logic/parser/UninurseBookParser.java, src/main/java/seedu/uninurse/model/Model.java, src/main/java/seedu/uninurse/model/ModelManager.java, src/main/java/seedu/uninurse/model/PersistentUninurseBook.java, src/main/java/seedu/uninurse/model/UninurseBookSnapshot.java, src/test/java/seedu/uninurse/logic/commands/AddPatientCommandTest.java
Resolves #40.
The undo limit is configured in `Config` under the name `UNDO_LIMIT`. Currently, it is set to 100.
=> Add undo and redo command

src/main/java/seedu/uninurse/MainApp.java
=> Update version number to v1.3

src/main/java/seedu/uninurse/model/task/TaskList.java
=> Fix task list indexing issue

src/main/java/seedu/uninurse/logic/commands/CommandResult.java, src/main/java/seedu/uninurse/logic/commands/CommandType.java, src/main/java/seedu/uninurse/logic/commands/ViewPatientCommand.java, src/main/java/seedu/uninurse/logic/parser/UninurseBookParser.java, src/main/java/seedu/uninurse/logic/parser/ViewPatientCommandParser.java, src/main/java/seedu/uninurse/model/ModelManager.java, src/main/java/seedu/uninurse/model/exceptions/PatientOfInterestNotFoundException.java, src/main/java/seedu/uninurse/ui/MainWindow.java, src/main/java/seedu/uninurse/ui/OutputPanel.java, src/test/java/seedu/uninurse/logic/commands/ViewPatientCommandTest.java, src/test/java/seedu/uninurse/logic/parser/ViewPatientCommandParserTest.java
=> Feature: view patient

src/test/java/seedu/uninurse/logic/commands/EditTaskCommandTest.java
This fixes a bug in `EditTaskCommandTest` as a prior PR was able to be merged before CI checks were completed.
=> Fix bug in PR merge

docs/UserGuide.md
Resolves #260, #210, and #209.
=> Update UG for `find`, `clear`, `undo`, and `redo` commands

src/main/java/seedu/uninurse/model/task/DateTime.java, src/main/java/seedu/uninurse/ui/TaskListCard.java
=> Feature UI - show DateTime for viewTask

docs/DeveloperGuide.md
=> Doc: update DG use cases for conditions and tags

src/main/java/seedu/uninurse/ui/UpdatedPatientCard.java, src/main/resources/view/Theme.css, src/main/resources/view/UpdatedPatientCard.fxml
Better look using more coloured borders.
=> Refine updated patient card

src/main/java/seedu/uninurse/logic/parser/ParserUtil.java
=> Fix options-based command syntax limit

src/main/java/seedu/uninurse/logic/commands/CommandResult.java, src/main/java/seedu/uninurse/logic/commands/EditTaskCommand.java, src/main/java/seedu/uninurse/logic/parser/EditTaskCommandParser.java, src/main/java/seedu/uninurse/logic/parser/ParserUtil.java, src/test/java/seedu/uninurse/logic/commands/EditTaskCommandTest.java, src/test/java/seedu/uninurse/logic/parser/EditTaskCommandParserTest.java
=> Fix edit task to work with custom formats

src/main/java/seedu/uninurse/model/task/RecurringTask.java
Closes #306. Additionally closes #350.
=> Fix recurrence time equality check for singular-plural form

docs/DeveloperGuide.md
Fix bug where diagram would show up in the TOC
=> Fix TOC bug in DG

docs/UserGuide.md
=> Improve `find` command documentation in User Guide

docs/team/izzahaj.md, src/main/java/seedu/uninurse/logic/commands/CommandResult.java
Incomplete. For Friday's submission.
=> Update 'Izzah's PPP draft

docs/DeveloperGuide.md, docs/team/shogun187.md
Update PPP and also minor change to the header for implementation in DG
=> Update Shaugn's PPP and DG

src/main/java/seedu/uninurse/commons/core/Messages.java, src/main/java/seedu/uninurse/logic/commands/AddConditionCommand.java, src/main/java/seedu/uninurse/logic/commands/AddTagCommand.java, src/main/java/seedu/uninurse/logic/commands/DeleteConditionCommand.java, src/main/java/seedu/uninurse/logic/commands/DeleteTagCommand.java, src/main/java/seedu/uninurse/logic/commands/EditConditionCommand.java, src/main/java/seedu/uninurse/logic/commands/EditTagCommand.java, src/main/java/seedu/uninurse/logic/parser/AddTagCommandParser.java, src/main/java/seedu/uninurse/logic/parser/DeleteTagCommandParser.java, src/main/java/seedu/uninurse/logic/parser/EditTagCommandParser.java, src/main/java/seedu/uninurse/model/tag/Tag.java, src/main/java/seedu/uninurse/model/tag/TagList.java, src/test/java/seedu/uninurse/logic/commands/AddConditionCommandTest.java, src/test/java/seedu/uninurse/logic/commands/AddTagCommandTest.java, src/test/java/seedu/uninurse/logic/commands/DeleteConditionCommandTest.java, src/test/java/seedu/uninurse/logic/commands/DeleteTagCommandTest.java, src/test/java/seedu/uninurse/logic/commands/EditConditionCommandTest.java, src/test/java/seedu/uninurse/logic/commands/EditTagCommandTest.java, src/test/java/seedu/uninurse/logic/parser/AddConditionCommandParserTest.java, src/test/java/seedu/uninurse/logic/parser/AddTagCommandParserTest.java, src/test/java/seedu/uninurse/logic/parser/DeleteConditionCommandParserTest.java, src/test/java/seedu/uninurse/logic/parser/DeleteTagCommandParserTest.java, src/test/java/seedu/uninurse/logic/parser/EditTagCommandParserTest.java, src/test/java/seedu/uninurse/model/condition/ConditionListTest.java, src/test/java/seedu/uninurse/model/tag/TagListTest.java
Also added a null check for `TagList#edit()` method.
=> Fix coding standards for tag-related classes

docs/UserGuide.md
=> Fix UG inconsistencies

docs/UserGuide.md
=> Add overdue recurring task behavior and duplicate task criteria to UG

docs/DeveloperGuide.md, docs/UserGuide.md
Added Description, Components and Functionality subsections.
Also updated links to the table of contents in UG so pdf version doesn't link to the website itself.
=> Add subheadings to UI component section DG

docs/DeveloperGuide.md
=> Add page breaks to DG for pdf conversion
